//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JavaScriptEngineSwitcher.Core.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class Strings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"JavaScriptEngineSwitcher.Core.Resources.Strings",
#if NET40
				typeof(Strings).Assembly
#else
				typeof(Strings).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "The parameter '{0}' must be a non-empty string."
		/// </summary>
		public static string Common_ArgumentIsEmpty
		{
			get { return GetString("Common_ArgumentIsEmpty"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The parameter '{0}' must be a non-nullable."
		/// </summary>
		public static string Common_ArgumentIsNull
		{
			get { return GetString("Common_ArgumentIsNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Cannot convert object of type `{0}` to type `{1}`."
		/// </summary>
		public static string Common_CannotConvertObjectToType
		{
			get { return GetString("Common_CannotConvertObjectToType"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Can not convert value '{0}' of enumeration type `{1}` to value of enumeration type `{2}`."
		/// </summary>
		public static string Common_EnumValueConversionFailed
		{
			get { return GetString("Common_EnumValueConversionFailed"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "File '{0}' not exist."
		/// </summary>
		public static string Common_FileNotExist
		{
			get { return GetString("Common_FileNotExist"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Resource with name '{0}' is null."
		/// </summary>
		public static string Common_ResourceIsNull
		{
			get { return GetString("Common_ResourceIsNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "See the original error message: “{0}”."
		/// </summary>
		public static string Common_SeeOriginalErrorMessage
		{
			get { return GetString("Common_SeeOriginalErrorMessage"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Value cannot be empty."
		/// </summary>
		public static string Common_ValueIsEmpty
		{
			get { return GetString("Common_ValueIsEmpty"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Value cannot be null."
		/// </summary>
		public static string Common_ValueIsNull
		{
			get { return GetString("Common_ValueIsNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Cannot convert null to a value type."
		/// </summary>
		public static string Common_ValueTypeCannotBeNull
		{
			get { return GetString("Common_ValueTypeCannotBeNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Name of default JavaScript engine not specified."
		/// </summary>
		public static string Configuration_DefaultJsEngineNameNotSpecified
		{
			get { return GetString("Configuration_DefaultJsEngineNameNotSpecified"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Could not find a factory, that creates an instance of the JavaScript engine with name `{0}`."
		/// </summary>
		public static string Configuration_JsEngineFactoryNotFound
		{
			get { return GetString("Configuration_JsEngineFactoryNotFound"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Most likely it happened, because the '{0}' assembly or one of its dependencies was not found."
		/// </summary>
		public static string Engine_AssemblyNotFound
		{
			get { return GetString("Engine_AssemblyNotFound"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Failed to create instance of the {0}."
		/// </summary>
		public static string Engine_JsEngineNotLoaded
		{
			get { return GetString("Engine_JsEngineNotLoaded"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "There is no {0} package for the {1} processor architecture."
		/// </summary>
		public static string Engine_NoNuGetPackageForProcessorArchitecture
		{
			get { return GetString("Engine_NoNuGetPackageForProcessorArchitecture"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Try to install the {0} package via NuGet."
		/// </summary>
		public static string Engine_NuGetPackageInstallationRequired
		{
			get { return GetString("Engine_NuGetPackageInstallationRequired"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Your operating system is not supported by the engine."
		/// </summary>
		public static string Engine_OperatingSystemNotSupported
		{
			get { return GetString("Engine_OperatingSystemNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "{0} processor architecture is not supported by the engine."
		/// </summary>
		public static string Engine_ProcessorArchitectureNotSupported
		{
			get { return GetString("Engine_ProcessorArchitectureNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Call stack"
		/// </summary>
		public static string ErrorDetails_CallStack
		{
			get { return GetString("ErrorDetails_CallStack"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Category"
		/// </summary>
		public static string ErrorDetails_Category
		{
			get { return GetString("ErrorDetails_Category"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Column number"
		/// </summary>
		public static string ErrorDetails_ColumnNumber
		{
			get { return GetString("ErrorDetails_ColumnNumber"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Description"
		/// </summary>
		public static string ErrorDetails_Description
		{
			get { return GetString("ErrorDetails_Description"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Document name"
		/// </summary>
		public static string ErrorDetails_DocumentName
		{
			get { return GetString("ErrorDetails_DocumentName"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Engine name"
		/// </summary>
		public static string ErrorDetails_EngineName
		{
			get { return GetString("ErrorDetails_EngineName"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Engine version"
		/// </summary>
		public static string ErrorDetails_EngineVersion
		{
			get { return GetString("ErrorDetails_EngineVersion"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Line number"
		/// </summary>
		public static string ErrorDetails_LineNumber
		{
			get { return GetString("ErrorDetails_LineNumber"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Message"
		/// </summary>
		public static string ErrorDetails_Message
		{
			get { return GetString("ErrorDetails_Message"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Source fragment"
		/// </summary>
		public static string ErrorDetails_SourceFragment
		{
			get { return GetString("ErrorDetails_SourceFragment"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Type"
		/// </summary>
		public static string ErrorDetails_Type
		{
			get { return GetString("ErrorDetails_Type"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The function with the name '{0}' does not exist."
		/// </summary>
		public static string Runtime_FunctionNotExist
		{
			get { return GetString("Runtime_FunctionNotExist"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The '{0}' line of the script error location has an incorrect format."
		/// </summary>
		public static string Runtime_InvalidErrorLocationLineFormat
		{
			get { return GetString("Runtime_InvalidErrorLocationLineFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Script execution was interrupted."
		/// </summary>
		public static string Runtime_ScriptInterrupted
		{
			get { return GetString("Runtime_ScriptInterrupted"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Script execution exceeded timeout."
		/// </summary>
		public static string Runtime_ScriptTimeoutExceeded
		{
			get { return GetString("Runtime_ScriptTimeoutExceeded"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The variable with the name '{0}' does not exist."
		/// </summary>
		public static string Runtime_VariableNotExist
		{
			get { return GetString("Runtime_VariableNotExist"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Cannot convert a pre-compiled script to internal type `{0}`."
		/// </summary>
		public static string Usage_CannotConvertPrecompiledScriptToInternalType
		{
			get { return GetString("Usage_CannotConvertPrecompiledScriptToInternalType"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Сannot execute a '{0}' file, because it is empty."
		/// </summary>
		public static string Usage_CannotExecuteEmptyFile
		{
			get { return GetString("Usage_CannotExecuteEmptyFile"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Сannot execute a '{0}' resource, because it is empty."
		/// </summary>
		public static string Usage_CannotExecuteEmptyResource
		{
			get { return GetString("Usage_CannotExecuteEmptyResource"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Сannot execute a pre-compiled script, because it was created for another JS engine with name `{0}`."
		/// </summary>
		public static string Usage_CannotExecutePrecompiledScriptForAnotherJsEngine
		{
			get { return GetString("Usage_CannotExecutePrecompiledScriptForAnotherJsEngine"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Сannot pre-compile a '{0}' file, because it is empty."
		/// </summary>
		public static string Usage_CannotPrecompileEmptyFile
		{
			get { return GetString("Usage_CannotPrecompileEmptyFile"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Сannot pre-compile a '{0}' resource, because it is empty."
		/// </summary>
		public static string Usage_CannotPrecompileEmptyResource
		{
			get { return GetString("Usage_CannotPrecompileEmptyResource"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The embedded host object '{0}' has a type `{1}`, which is not supported."
		/// </summary>
		public static string Usage_EmbeddedHostObjectTypeNotSupported
		{
			get { return GetString("Usage_EmbeddedHostObjectTypeNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The embedded host type `{0}` is not supported."
		/// </summary>
		public static string Usage_EmbeddedHostTypeNotSupported
		{
			get { return GetString("Usage_EmbeddedHostTypeNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "One of the function parameters '{0}' has a type `{1}`, which is not supported."
		/// </summary>
		public static string Usage_FunctionParameterTypeNotSupported
		{
			get { return GetString("Usage_FunctionParameterTypeNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The document name '{0}' has incorrect format."
		/// </summary>
		public static string Usage_InvalidDocumentNameFormat
		{
			get { return GetString("Usage_InvalidDocumentNameFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The file name '{0}' has incorrect format."
		/// </summary>
		public static string Usage_InvalidFileNameFormat
		{
			get { return GetString("Usage_InvalidFileNameFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The function name '{0}' has incorrect format."
		/// </summary>
		public static string Usage_InvalidFunctionNameFormat
		{
			get { return GetString("Usage_InvalidFunctionNameFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The resource name '{0}' has incorrect format."
		/// </summary>
		public static string Usage_InvalidResourceNameFormat
		{
			get { return GetString("Usage_InvalidResourceNameFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The script item name '{0}' has incorrect format."
		/// </summary>
		public static string Usage_InvalidScriptItemNameFormat
		{
			get { return GetString("Usage_InvalidScriptItemNameFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The variable name '{0}' has incorrect format."
		/// </summary>
		public static string Usage_InvalidVariableNameFormat
		{
			get { return GetString("Usage_InvalidVariableNameFormat"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The type of return value `{0}` is not supported."
		/// </summary>
		public static string Usage_ReturnValueTypeNotSupported
		{
			get { return GetString("Usage_ReturnValueTypeNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The variable '{0}' has a type `{1}`, which is not supported."
		/// </summary>
		public static string Usage_VariableTypeNotSupported
		{
			get { return GetString("Usage_VariableTypeNotSupported"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}