//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaScriptEngineSwitcher.ChakraCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JavaScriptEngineSwitcher.ChakraCore.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the &apos;{0}&apos; directory to the search path used to locate DLLs for the application..
        /// </summary>
        internal static string Engines_AddingDirectoryToDllSearchPathFailed {
            get {
                return ResourceManager.GetString("Engines_AddingDirectoryToDllSearchPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directory, that should contain `ChakraCore.dll` assembly, does not exist..
        /// </summary>
        internal static string Engines_ChakraCoreAssemblyDirectoryNotFound {
            get {
                return ResourceManager.GetString("Engines_ChakraCoreAssemblyDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During invocation of the host delegate an error has occurred - “{0}”..
        /// </summary>
        internal static string Runtime_HostDelegateInvocationFailed {
            get {
                return ResourceManager.GetString("Runtime_HostDelegateInvocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During getting value of &apos;{0}&apos; field of the host object an error has occurred - “{1}”..
        /// </summary>
        internal static string Runtime_HostObjectFieldGettingFailed {
            get {
                return ResourceManager.GetString("Runtime_HostObjectFieldGettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During setting value of &apos;{0}&apos; field of the host object an error has occurred - “{1}”..
        /// </summary>
        internal static string Runtime_HostObjectFieldSettingFailed {
            get {
                return ResourceManager.GetString("Runtime_HostObjectFieldSettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During invocation of &apos;{0}&apos; method of the host object an error has occurred - “{1}”..
        /// </summary>
        internal static string Runtime_HostObjectMethodInvocationFailed {
            get {
                return ResourceManager.GetString("Runtime_HostObjectMethodInvocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During getting value of &apos;{0}&apos; property of the host object an error has occurred - “{1}”..
        /// </summary>
        internal static string Runtime_HostObjectPropertyGettingFailed {
            get {
                return ResourceManager.GetString("Runtime_HostObjectPropertyGettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During setting value of &apos;{0}&apos; property of the host object an error has occurred - “{1}”..
        /// </summary>
        internal static string Runtime_HostObjectPropertySettingFailed {
            get {
                return ResourceManager.GetString("Runtime_HostObjectPropertySettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve field &apos;{0}&apos; of the host object, because there was an invalid `this` context..
        /// </summary>
        internal static string Runtime_InvalidThisContextForHostObjectField {
            get {
                return ResourceManager.GetString("Runtime_InvalidThisContextForHostObjectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not call method &apos;{0}&apos; of the host object, because there was an invalid `this` context..
        /// </summary>
        internal static string Runtime_InvalidThisContextForHostObjectMethod {
            get {
                return ResourceManager.GetString("Runtime_InvalidThisContextForHostObjectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve property &apos;{0}&apos; of the host object, because there was an invalid `this` context..
        /// </summary>
        internal static string Runtime_InvalidThisContextForHostObjectProperty {
            get {
                return ResourceManager.GetString("Runtime_InvalidThisContextForHostObjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find suitable method or not enough arguments to invoke of &apos;{0}&apos; method of the host object..
        /// </summary>
        internal static string Runtime_SuitableMethodOfHostObjectNotFound {
            get {
                return ResourceManager.GetString("Runtime_SuitableMethodOfHostObjectNotFound", resourceCulture);
            }
        }
    }
}
