//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaScriptEngineSwitcher.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JavaScriptEngineSwitcher.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must be a non-empty string..
        /// </summary>
        public static string Common_ArgumentIsEmpty {
            get {
                return ResourceManager.GetString("Common_ArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must be a non-nullable..
        /// </summary>
        public static string Common_ArgumentIsNull {
            get {
                return ResourceManager.GetString("Common_ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not specified a name of assembly..
        /// </summary>
        public static string Common_AssemblyNameIsEmpty {
            get {
                return ResourceManager.GetString("Common_AssemblyNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert value &apos;{0}&apos; of enumeration type `{1}` to value of enumeration type `{2}`..
        /// </summary>
        public static string Common_EnumValueConversionFailed {
            get {
                return ResourceManager.GetString("Common_EnumValueConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not exist..
        /// </summary>
        public static string Common_FileNotExist {
            get {
                return ResourceManager.GetString("Common_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During instantiate an object of type `{0}` from assembly `{1}` error occurred..
        /// </summary>
        public static string Common_InstanceCreationFailed {
            get {
                return ResourceManager.GetString("Common_InstanceCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not specified a type name..
        /// </summary>
        public static string Common_TypeNameIsEmpty {
            get {
                return ResourceManager.GetString("Common_TypeNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string Common_ValueIsEmpty {
            get {
                return ResourceManager.GetString("Common_ValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        public static string Common_ValueIsNull {
            get {
                return ResourceManager.GetString("Common_ValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default JavaScript engine not specified..
        /// </summary>
        public static string Configuration_DefaultJsEngineNotSpecified {
            get {
                return ResourceManager.GetString("Configuration_DefaultJsEngineNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript engine with name `{0}` is not registered in configuration file..
        /// </summary>
        public static string Configuration_JsEngineNotRegistered {
            get {
                return ResourceManager.GetString("Configuration_JsEngineNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ErrorDetails_Category {
            get {
                return ResourceManager.GetString("ErrorDetails_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column number.
        /// </summary>
        public static string ErrorDetails_ColumnNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine name.
        /// </summary>
        public static string ErrorDetails_EngineName {
            get {
                return ResourceManager.GetString("ErrorDetails_EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine version.
        /// </summary>
        public static string ErrorDetails_EngineVersion {
            get {
                return ResourceManager.GetString("ErrorDetails_EngineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        public static string ErrorDetails_ErrorCode {
            get {
                return ResourceManager.GetString("ErrorDetails_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        public static string ErrorDetails_LineNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ErrorDetails_Message {
            get {
                return ResourceManager.GetString("ErrorDetails_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source fragment.
        /// </summary>
        public static string ErrorDetails_SourceFragment {
            get {
                return ResourceManager.GetString("ErrorDetails_SourceFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource with name &apos;{0}&apos; is null..
        /// </summary>
        public static string Resources_ResourceIsNull {
            get {
                return ResourceManager.GetString("Resources_ResourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; is forbidden, as is contained in the list of reserved words of JavaScript language..
        /// </summary>
        public static string Runtime_FunctionNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_FunctionNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the function parameters &apos;{0}&apos; has a type `{1}`, which is not supported..
        /// </summary>
        public static string Runtime_FunctionParameterTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_FunctionParameterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; has incorrect format..
        /// </summary>
        public static string Runtime_InvalidFunctionNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidFunctionNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name &apos;{0}&apos; has incorrect format..
        /// </summary>
        public static string Runtime_InvalidVariableNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidVariableNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During loading of {0} error has occurred.	
        ///See more details:
        ///
        ///{1}.
        /// </summary>
        public static string Runtime_JsEngineNotLoaded {
            get {
                return ResourceManager.GetString("Runtime_JsEngineNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load information about the method &apos;{1}&apos; of type `{0}`..
        /// </summary>
        public static string Runtime_MethodInfoNotLoaded {
            get {
                return ResourceManager.GetString("Runtime_MethodInfoNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of return value `{0}` is not supported..
        /// </summary>
        public static string Runtime_ReturnValueTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_ReturnValueTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name &apos;{0}&apos; is forbidden, as is contained in the list of reserved words of JavaScript language..
        /// </summary>
        public static string Runtime_VariableNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_VariableNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; has a type `{1}`, which is not supported..
        /// </summary>
        public static string Runtime_VariableTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_VariableTypeNotSupported", resourceCulture);
            }
        }
    }
}
