//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JavaScriptEngineSwitcher.V8.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class Strings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"JavaScriptEngineSwitcher.V8.Resources.Strings",
#if NETSTANDARD1_0 || NETSTANDARD1_1 || NETSTANDARD1_2 || NETSTANDARD1_3 || NETSTANDARD1_4 || NETSTANDARD1_5 || NETSTANDARD1_6 || NETCOREAPP1_0 || NET451 || NET452 || NET46 || NET461 || NET462 || NET463
				typeof(Strings).GetTypeInfo().Assembly
#elif NET40
				typeof(Strings).Assembly
#else
#error No implementation for this target
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Failed to load the ClearScript `undefined` value."
		/// </summary>
		public static string Engines_ClearScriptUndefinedValueNotLoaded
		{
			get { return GetString("Engines_ClearScriptUndefinedValueNotLoaded"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Failed to load the ClearScriptV8 assembly, because the directory '{0}' does not exist."
		/// </summary>
		public static string Engines_ClearScriptV8AssembliesDirectoryNotFound
		{
			get { return GetString("Engines_ClearScriptV8AssembliesDirectoryNotFound"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Failed to load the ClearScriptV8 assembly, because the file '{0}' does not exist."
		/// </summary>
		public static string Engines_ClearScriptV8AssemblyFileNotFound
		{
			get { return GetString("Engines_ClearScriptV8AssemblyFileNotFound"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Failed to load information about the method '{1}' of type `{0}`."
		/// </summary>
		public static string Runtime_MethodInfoNotLoaded
		{
			get { return GetString("Runtime_MethodInfoNotLoaded"); }
		}

			private static string GetString(string name)
			{
				string value = ResourceManager.GetString(name, _resourceCulture);

				return value;
			}
		}
	}