//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JavaScriptEngineSwitcher.Vroom.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	internal class Strings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"JavaScriptEngineSwitcher.Vroom.Resources.Strings",
#if NET20 || NET30 || NET35 || NET40
				typeof(Strings).Assembly
#else
				typeof(Strings).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		internal static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		internal static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Serialization of type `{0}` is not supported."
		/// </summary>
		internal static string Common_CannotSerializeType
		{
			get { return GetString("Common_CannotSerializeType"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "You can build the '{0}' and '{1}' assemblies by using following instructions from official..."
		/// </summary>
		internal static string Engine_BuildNativeAssemblies
		{
			get { return GetString("Engine_BuildNativeAssemblies"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Try to install the Visual C++ Redistributable for Visual Studio 2012..."
		/// </summary>
		internal static string Engine_VcRedist2012And2015InstallationRequired
		{
			get { return GetString("Engine_VcRedist2012And2015InstallationRequired"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}