//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace JavaScriptEngineSwitcher.Sample.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class EvaluationStrings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"JavaScriptEngineSwitcher.Sample.Resources.EvaluationStrings",
#if NETSTANDARD1_0 || NETSTANDARD1_1 || NETSTANDARD1_2 || NETSTANDARD1_3 || NETSTANDARD1_4 || NETSTANDARD1_5 || NETSTANDARD1_6 || NETSTANDARD2_0 || NETCOREAPP1_0 || NETCOREAPP2_0 || NET45 || NET451 || NET452 || NET46 || NET461 || NET462 || NET463
				typeof(EvaluationStrings).GetTypeInfo().Assembly
#elif NET40
				typeof(EvaluationStrings).Assembly
#else
#error No implementation for this target
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Evaluate"
		/// </summary>
		public static string ButtonText_Evaluate
		{
			get { return GetString("ButtonText_Evaluate"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Engine"
		/// </summary>
		public static string DisplayName_EngineName
		{
			get { return GetString("DisplayName_EngineName"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Expression"
		/// </summary>
		public static string DisplayName_Expression
		{
			get { return GetString("DisplayName_Expression"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Result"
		/// </summary>
		public static string DisplayName_ResultValue
		{
			get { return GetString("DisplayName_ResultValue"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "You did not fill field &quot;{0}&quot;."
		/// </summary>
		public static string ErrorMessage_FormFieldIsNotFilled
		{
			get { return GetString("ErrorMessage_FormFieldIsNotFilled"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The field &quot;{0}&quot; must be a string with a maximum length of {1:N0}."
		/// </summary>
		public static string ErrorMessage_FormFieldValueTooLong
		{
			get { return GetString("ErrorMessage_FormFieldValueTooLong"); }
		}

			private static string GetString(string name)
			{
				string value = ResourceManager.GetString(name, _resourceCulture);

				return value;
			}
		}
	}